Repository cybertec-postgresql/vip-manager, pull requests merged in 2023-02, with the labels that each got.

#136 [-] remove copyright leftovers, fixes #135
  iphlpapi/mksyscall.go
Labels: go

#133 Allow etcd3 as additional spelling of etcd dcs-type.
  checker/leader_checker.go
  vipconfig/config.go
Labels: enhancement

#138 [+] add CodeQL GHA workflow
  .github/workflows/codeql-analysis.yml
Labels: enhancement, github_actions
